command /teleports [<number>]:
    trigger:
        arg-1 is 1:
            teleport player to location at -47.5, 231, -137.5 in world "world"       
        arg-1 is 2:
            teleport player to location at -40, 147, 22 in world "world"            
        arg-1 is 3:
            teleport player to location at -337, 171.00, 50 in world "world"
        arg-1 is 4:
            teleport player to location at -27, 115, 170 in world "world"